name: eleventhdemoMaintoberun (Calc-Co Main Delivery)

on:
  workflow_dispatch:

jobs:
  # The Boss calls the Reusable Workflow
  execute-enterprise-pipeline:
    uses: ./.github/workflows/eleventhdemo-support.yml
